#!/usr/bin/env bash

## About LunaWolf Linux

## Get ISO Version
if [[ -e '/version' ]]; then
	version="v`cat /version | cut -d'.' -f1`.`cat /version | cut -d '.' -f2`"
else
	version='rolling'
fi

yad --title='About LunaWolf Linux' --window-icon='lunawolf-cyan' \
	--about \
	--pname='LunaWolf Linux' \
	--pversion="$version" \
	--image='lunawolf-cyan' \
	--comments="A Lightweight Arch Linux based distribution aimed at software developers and general linux users." \
	--copyright="Copyright `date +'%Y'`, HypherionSA <hypherionmc.com>" \
	--license='GPL3' \
	--website='https://lunawolf.cc' \
	--website-label='lunawolf.cc' \
	--authors="HypherionSA <hypherionmc.com>"